Update linux-build.yml

diff --git a/.github/workflows/linux-build.yml b/.github/workflows/linux-build.yml
--- a/.github/workflows/linux-build.yml
+++ b/.github/workflows/linux-build.yml
@@ -22,9 +22,9 @@ jobs:
 
       - name: List source files
         run: |
-         ls -la Engine/Source/GameFramework/
-         ls -la Engine/Source/GameFramework/Controller/ || echo "Controller folder not found"
-         ls -la Engine/Source/GameFramework/GameObjects/ || echo "GameObjects folder not found"
+         ls -la Source/GameFramework/
+         ls -la Source/GameFramework/Controller/ || echo "Controller folder not found"
+         ls -la Source/GameFramework/GameObjects/ || echo "GameObjects folder not found"
       
       - name: Install Conan
         run: pip install conan
